---
title: "metadata"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
library(dplyr)
```

# Obtain whole blood gene expression samples
```{r}
# Load the gene expression data
gene_expr_file <- "data/gene_reads_2017-06-05_v8_whole_blood.gct"
raw_count_df <- fread(gene_expr_file, header = TRUE)
raw_count_df <- raw_count_df[, -c(1:3)]

# modify GTEx sample names matching names used in PRS data
colnames(raw_count_df) <- sub("^(GTEX-[^-.]+).*", "\\1", colnames(raw_count_df))
```

# Match samples between PRS and count matrix
```{r}
# load PRS data for blood trait
prs_file <- "analysis/prs_blood_cell.txt"
prs_blood <- fread(prs_file, header = T, stringsAsFactors = FALSE)

# obtain GTEx sample id
id <- prs_blood$sample_id

# Load the PRS data for immune trait
prs_file <- "analysis/prs_immune.txt"
prs_immune <- fread(prs_file, header = T, stringsAsFactors = FALSE)

# subset samples
matching_samples <- intersect(id, colnames(raw_count_df))
prs_blood <- prs_blood[prs_blood$sample_id %in% matching_samples, ]
prs_immune <- prs_immune[prs_immune$sample_id %in% matching_samples, ]
```

# Whole blood covariates 
```{r}
cov_file <- "data/Whole_Blood.v8.covariates.txt"
cov <- fread(cov_file, header = T, stringsAsFactors = FALSE)
cov <- cov %>% filter(ID %in% c(paste0("PC", 1:5), "sex"))
col <- cov$ID
cov <- as.matrix(t(cov[, -1])) 
colnames(cov) <- col
```

# Create metadata for continuous traits
```{r}
# continuous traits
metadata <- cbind(cov, prs_blood[, 2:30], prs_immune[,2:9])
rownames(metadata) <- matching_samples
metadata$sex <- as.factor(metadata$sex)
head(metadata)
write.table(metadata, "analysis/metadata.txt", sep="\t", row.names = T,
            col.names = T, quote = F)
```


# Stratify by PRS level (High vs Median vs Low)
## Blood trait
```{r}
for (i in 2:ncol(prs_blood)) {
  # Extract the PRS values for the current trait
  prs_trait <- prs_blood[[i]]

  # Calculate the 75th percentile for the trait (top 25% threshold)
  p75 <- quantile(prs_trait, 0.75, na.rm = TRUE)

  # Create a new column for the group classification based on the 75th percentile
  group <- ifelse(prs_trait > p75, "Top 25%", "Remaining")

  # Assign the group to the new column for this trait
  prs_blood[[colnames(prs_blood)[i]]] <- factor(group, 
                                      levels = c("Remaining", "Top 25%"))
}
```

## Immune trait
```{r}
for (i in 2:ncol(prs_immune)) {
  # Extract the PRS values for the current trait
  prs_trait <- prs_immune[[i]]

  # Calculate the 75th percentile for the trait (top 25% threshold)
  p75 <- quantile(prs_trait, 0.75, na.rm = TRUE)

  # Create a new column for the group classification based on the 75th percentile
  group <- ifelse(prs_trait > p75, "Top 25%", "Remaining")

  # Assign the group to the new column for this trait
  prs_immune[[colnames(prs_immune)[i]]] <- factor(group, 
                                      levels = c("Remaining", "Top 25%"))
}
```

# Create metadata for quantile traits into top 25% & remaining
```{r}
metadata <- cbind(cov, prs_blood[, 2:30], prs_immune[,2:9])
rownames(metadata) <- matching_samples
metadata$sex <- as.factor(metadata$sex)
head(metadata)
write.table(metadata, "analysis/metadata_quantile.txt", sep="\t", row.names = T,
            col.names = T, quote = F)
```



