---
title: "QC"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pheatmap)
library(DESeq2)
library(ggplot2)
```

# PCA 
```{r}
load("analysis/vst norm counts.rda")

metadata_file <- "analysis/metadata.txt"
metadata <- read.csv(metadata_file, header = T, sep = "\t", stringsAsFactors = T)
metadata$sex <- as.factor(metadata$sex)

group_columns <- grep("^group_", colnames(metadata), value = TRUE)

for (group in group_columns) {
  # Plot PCA for the current group
  pca_plot <- plotPCA(dds.vsd, intgroup = group) + 
    labs(title = paste("PCA for", group))
  
  # Print the plot
  print(pca_plot)
}
```


There is no clear clustering on the PCA plot across traits, suggesting that there are no strong, patterns in the data.

# heatmap of sample-to-sample distance
```{r}
sampleDists <- dist(t(assay(dds.vsd)))
sampleDistMatrix <- as.matrix(sampleDists)
rownames(sampleDistMatrix) <- rownames(metadata)
colnames(sampleDistMatrix) <- NULL
pheatmap(sampleDistMatrix,
         clustering_distance_rows=sampleDists,
         clustering_distance_cols=sampleDists
         )
```
